[2023-12-10 22:06:50,810] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:01:46.891631+00:00 [queued]>
[2023-12-10 22:06:50,815] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:01:46.891631+00:00 [queued]>
[2023-12-10 22:06:50,816] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:06:50,816] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2023-12-10 22:06:50,816] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:06:50,826] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_create> on 2023-12-10 17:01:46.891631+00:00
[2023-12-10 22:06:50,829] {standard_task_runner.py:52} INFO - Started process 20333 to run task
[2023-12-10 22:06:50,833] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline', 'data_create', 'manual__2023-12-10T17:01:46.891631+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/final_script.py', '--cfg-path', '/tmp/tmpai5zo83e', '--error-file', '/tmp/tmp7y_qsq2f']
[2023-12-10 22:06:50,834] {standard_task_runner.py:80} INFO - Job 14: Subtask data_create
[2023-12-10 22:06:50,859] {task_command.py:369} INFO - Running <TaskInstance: pipeline.data_create manual__2023-12-10T17:01:46.891631+00:00 [running]> on host vmac-VirtualBox
[2023-12-10 22:06:50,972] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=pipeline
AIRFLOW_CTX_TASK_ID=data_create
AIRFLOW_CTX_EXECUTION_DATE=2023-12-10T17:01:46.891631+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-10T17:01:46.891631+00:00
[2023-12-10 22:06:50,972] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 22:06:50,973] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/vmac/lab3/scripts/data_create.py']
[2023-12-10 22:06:50,978] {subprocess.py:85} INFO - Output:
[2023-12-10 22:06:52,580] {subprocess.py:92} INFO - Downloading...
[2023-12-10 22:06:52,580] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=1d23lf2o2-kYa631W_byvQv1Xu6sQ8Bgw
[2023-12-10 22:06:52,580] {subprocess.py:92} INFO - To: /home/vmac/lab3/dataset/dataset.csv
[2023-12-10 22:06:53,325] {subprocess.py:92} INFO -   0%|          | 0.00/3.95M [00:00<?, ?B/s] 13%|█▎        | 524k/3.95M [00:00<00:02, 1.65MB/s] 27%|██▋       | 1.05M/3.95M [00:00<00:01, 2.46MB/s] 53%|█████▎    | 2.10M/3.95M [00:00<00:00, 4.66MB/s] 80%|███████▉  | 3.15M/3.95M [00:00<00:00, 5.74MB/s]100%|██████████| 3.95M/3.95M [00:00<00:00, 5.34MB/s]
[2023-12-10 22:06:53,355] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 22:06:53,693] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=data_create, execution_date=20231210T170146, start_date=20231210T170650, end_date=20231210T170653
[2023-12-10 22:06:54,460] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 22:06:54,481] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
