[2023-12-10 22:39:03,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:38:59.901032+00:00 [queued]>
[2023-12-10 22:39:03,258] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: pipeline.data_create manual__2023-12-10T17:38:59.901032+00:00 [queued]>
[2023-12-10 22:39:03,258] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:39:03,258] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2023-12-10 22:39:03,258] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 22:39:03,280] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): data_create> on 2023-12-10 17:38:59.901032+00:00
[2023-12-10 22:39:03,285] {standard_task_runner.py:52} INFO - Started process 25736 to run task
[2023-12-10 22:39:03,295] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'pipeline', 'data_create', 'manual__2023-12-10T17:38:59.901032+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/final_script.py', '--cfg-path', '/tmp/tmpcbf39rbw', '--error-file', '/tmp/tmppghp492p']
[2023-12-10 22:39:03,296] {standard_task_runner.py:80} INFO - Job 24: Subtask data_create
[2023-12-10 22:39:03,337] {task_command.py:369} INFO - Running <TaskInstance: pipeline.data_create manual__2023-12-10T17:38:59.901032+00:00 [running]> on host vmac-VirtualBox
[2023-12-10 22:39:03,414] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Admin
AIRFLOW_CTX_DAG_ID=pipeline
AIRFLOW_CTX_TASK_ID=data_create
AIRFLOW_CTX_EXECUTION_DATE=2023-12-10T17:38:59.901032+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-10T17:38:59.901032+00:00
[2023-12-10 22:39:03,414] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 22:39:03,415] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/vmac/lab3/scripts/data_create.py']
[2023-12-10 22:39:03,436] {subprocess.py:85} INFO - Output:
[2023-12-10 22:39:05,077] {subprocess.py:92} INFO - Downloading...
[2023-12-10 22:39:05,077] {subprocess.py:92} INFO - From: https://drive.google.com/uc?id=1d23lf2o2-kYa631W_byvQv1Xu6sQ8Bgw
[2023-12-10 22:39:05,077] {subprocess.py:92} INFO - To: /home/vmac/lab3/dataset/dataset.csv
[2023-12-10 22:39:05,609] {subprocess.py:92} INFO -   0%|          | 0.00/3.95M [00:00<?, ?B/s] 13%|█▎        | 524k/3.95M [00:00<00:01, 2.95MB/s] 40%|███▉      | 1.57M/3.95M [00:00<00:00, 5.62MB/s] 66%|██████▋   | 2.62M/3.95M [00:00<00:00, 6.53MB/s]100%|██████████| 3.95M/3.95M [00:00<00:00, 7.54MB/s]
[2023-12-10 22:39:05,662] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 22:39:05,689] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=data_create, execution_date=20231210T173859, start_date=20231210T173903, end_date=20231210T173905
[2023-12-10 22:39:05,728] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 22:39:05,753] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
